# Generated by Django 3.2.6 on 2021-09-06 19:42

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('quality', models.CharField(blank=True, choices=[('HD', 'HD'), ('HDRip', 'HDRip'), ('SD', 'SD'), ('TS', 'TS'), ('CAM', 'CAM')], max_length=5, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Home.models.images_slider)),
                ('genre1', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Thriller', 'Thriller')], max_length=15, null=True)),
                ('genre2', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Thriller', 'Thriller')], max_length=15, null=True)),
                ('genre3', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Thriller', 'Thriller')], max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('Watch Now', 'Watch Now'), ('Coming Soon', 'Coming Soon')], max_length=15, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV-Series', 'TV-Series')], max_length=15, null=True)),
            ],
        ),
    ]
