# Generated by Django 3.2.6 on 2021-09-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='genre1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='genre2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='genre3',
        ),
        migrations.AddField(
            model_name='slider',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Home.category'),
        ),
    ]
