# Generated by Django 3.2.6 on 2021-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210906_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
