# Generated by Django 3.2.6 on 2021-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_category_slider_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='iframeurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
