# Generated by Django 3.2.6 on 2021-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_slider_imageposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='actors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='directors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='gener',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='quntry',
            field=models.CharField(blank=True, choices=[('Europ', 'Europ'), ('International', 'International'), ('United State', 'United State')], max_length=15, null=True),
        ),
    ]
