# Generated by Django 3.2.6 on 2021-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_trailer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
