# Generated by Django 3.2.6 on 2021-09-16 11:36

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_trailer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.images_trailer),
        ),
    ]
