# Generated by Django 3.2.6 on 2021-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_trailer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
