# Generated by Django 3.2.6 on 2021-09-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20210925_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newrelease',
        ),
        migrations.DeleteModel(
            name='Submovie',
        ),
    ]
