# Generated by Django 3.2.6 on 2021-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Iframemovie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
