# Generated by Django 3.2.6 on 2021-12-11 17:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_alter_movie_iframemovie'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('movietitle', django.db.models.manager.Manager()),
            ],
        ),
    ]
