# Generated by Django 3.2.6 on 2021-12-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_alter_movie_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
    ]
